[project]
name = "scraper-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "fastapi>=0.141.1",
    "google-generativeai>=0.8.6",
    "httpx>=0.28.1",
    "litellm>=1.100.0",
    "pillow>=12.3.0",
    "playwright>=1.62.0",
    "psycopg2-binary>=2.9.11",
    "pytesseract>=0.3.13",
    "python-dotenv>=1.2.3",
    "redis>=8.1.0",
    "selectolax>=0.4.11",
    "uvicorn[standard]>=0.52.4",
]

[project.scripts]
scraper-service = "scraper_service:main"

[build-system]
requires = ["uv_build>=0.12.11,<0.13.0"]
build-backend = "uv_build"
